// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DAL
{
    public partial interface IAppDbContextProcedures
    {
        Task<int> AddNewProductDetailsAsync(string Name, string Description, decimal? UnitPrice, int? CategoryId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteProductByIdAsync(int? ProductId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateProductDetailsAsync(int? ProductId, string Name, string Description, decimal? UnitPrice, int? CategoryId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getproductResult>> usp_getproductAsync(int? ProductId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
